language: ruby
rvm:
  - "2.0.0"
before_install: 
  - gem update --system
  - gem --version
before_script:
  - bundle exec rake assets:precompile
# uncomment only this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
